>P1;cox2_parde
cox2_parde  298 bases  CC968400 checksum
MMAIATKRRGVAAVMSLGVATMTAVPALAQDVLGDLPVIGKPVNGGMNFQPASSPLAHDQ
QWLDHFVLYIITAVTIFVCLLLLICIVRFNRR--ANPVPAR-------------------
--------FTHNTPIEVIWTLVPVLILVAIGAFSLPILFRSQEMPNDPDLVIKAIGHQWY
WSYEYPNDG------------------------------------------------VAF
DALMLEKEALADAGYSEDEYLLATDNPVVVPVGKKVLVQVTATDVIHAWTIPAFAVKQDA
VPGRIAQLWFSVDQEGVYFGQCSELCGINHAYMPIVVKAVSQEKYEAWLAGAKEEFAADA
SDYLPASPVKLASAE
*
>P1;cox2_acaca
cox2_acaca  319 bases  75B5866C checksum
-----------------------------------LCLNDHTNSWKIGFQDPTTPIAYGI
IKLHDHILFFLAVILFVVGYLLLSTYKKFYYGSLNNDLPESKRISLFDTLINTYKENLSF
NVTNRTYNINHGTTIEIIWTILPAFILLFIAVPSFALLYAMDEII-DPVLTVKVIGHQWY
WSYEYSDYSVVYSNRMLDYDSIDRFAAMEMMYKGMGYLKDRSLLSYLYIPMVIPETTIKF
DSYMIHEAELNLGDLR----LLKTDMPLFLPKNTHIRLLITSSDVLHSWAVPSFGVKVDA
VPGRLNQTSLYLKNTGTFYGQCSELCGVNHAFMPIEVYVVNPVYFYNYVYIYFKNFNLI-
---------------
*
>P1;cox2_allma
cox2_allma  245 bases  94FF63EF checksum
-------------------------MKLLN-----FIYNDHPQPWQIGFQDGATTTFYGI
VDLHDNIIFYLIIVIIGVTWIQTSVMLDSYGN--SDKHVYK-------------------
-------YSHHGTLVEIIWTITPALILVAIAFPSFKLLYLMDSVV-DPAVTVKAIGYQWY
WGYNYGDYN----------------------------------------------EDISF
DSFMVPTDELEMGQFR----LLEVDNRVVVPVDTRVRIVVTAADVIHSFAVPSLGIKIDA
IPGRINQASFLIDREGVYYGQCSELCGANHGFMPIAIEAVSLDRYVAWVDAQLS------
---------------
*
>P1;cox2_apec
cox2_apec  229 bases  7130EE9B checksum
----------------------------------------MANWTQLGLQDASSPLMEEL
IYFHDYTLIILTLITILVFYGLASLLFS--------SNTN--------------------
------RFFLEGQGLETVWTIIPAVILIFIALPSLQLLYLMDEVN-NPYLTIKAIGHQWY
WSYEYADYR-----------------------------------------------ELEF
DSYMIPTSDLTSGNPR----LLEVDNRLTLPAQTPIRVLVSSADVLHSWAIPSLGIKMDA
VPGRLNQVNFFISRCGLFYGQCSEICGANHSFMPIVIESVNFSTFETWVSNFITE-----
---------------
*
>P1;cox2_arath
cox2_arath  260 bases  E40CAEA4 checksum
--------------------MIVLKWLFLT-----ISPCDAAEPWQLGSQDAATPIMQGI
IDLHHDIFFFLILILVFVLWILVRALWHFHYK--KNAIPQR-------------------
--------IVHGTTIEILRTIFPSIISMFIAIPSFALLYSMDEVVVDPAITIKAIGHQWY
RTYEYSDYNSS------------------------------------------DEQSLTF
DSYMIPEEDLELGQSR----LLEVDNRVVVPAKTHLRIIVTSADVPHSWAVPSSGVKCDA
VPGRLNQISILVQREGVYYGQCSEICGTNHAFTSIVVEAVPRKDYGSRVSNQLIPQTGEA
---------------
*
>P1;cox2_balca
cox2_balca  228 bases  95668854 checksum
----------------------------------------MATWAQLGFQDAASPIMEEL
IYFHDHALVILTLVTIIVFYGLISLITN--------SFTN--------------------
------RFLLEGQEIETIWTIIPAIILIFLALPSLRLLYLMDEIN-DPHLTIKAIGHQWY
WSYEYTDYQ-----------------------------------------------DLEF
DSYMVPTQDLTPGQPR----LLEVDNRLVAPTHSPVRVLVTSADVLHSWAIPALGLKMDA
VPGRLNQLTFFAPRSGVFYGQCSEICGANHSFMPIVLESVPLPYFENWVSSLVE------
---------------
*
>P1;cox2_chocr
cox2_chocr  254 bases  A9D75E5F checksum
--------------------MNNILNFYPA-----VITTDVAENWQIGFQDPATPIMEGI
INLHYDLMFFICVISVFVSWMLGRTLWHFEQN--QNKIPSS-------------------
--------LTHGTLIEMIWTVTPAFILLIIAVPSFSLLYAMDEII-SPAITIKTLGHQWY
WSYEYSDYLNE------------------------------------------DDDSINY
DSYMIPEEDLEIGQFR----LLEVDNRMVIPINTHIRVIVTAADVLHSWAVPSFRSKCDA
IPGRLNQTSLFIKREGVYYGQCSEICGINHGFMPIVVEATSLPNYVSWISNKLNE-----
---------------
*
>P1;cox2_drome
cox2_drome  228 bases  173CB812 checksum
----------------------------------------MSTWANLGLQDSASPLMEQL
IFFHDHALLILVMITVLVGYLMFMLFFN--------NYVN--------------------
------RFLLHGQLIEMIWTILPAIILLFIALPSLRLLYLLDEIN-EPSVTLKSIGHQWY
WSYEYSDFN-----------------------------------------------NIEF
DSYMIPTNELMTDGFR----LLDVDNRVVLPMNSQIRILVTAADVIHSWTVPALGVKVDG
TPGRLNQTNFFINRPGLFYGQCSEICGANHSFMPIVIESVPVNYFIKWISSNNS------
---------------
*
>P1;cox2_human
cox2_human  227 bases  C832EB46 checksum
----------------------------------------MAHAAQVGLQDATSPIMEEL
ITFHDHALMIIFLICFLVLYALFLTLTT--------KLTN--------------------
------TNISDAQEMETVWTILPAIILVLIALPSLRILYMTDEVN-DPSLTIKSIGHQWY
WTYEYTDYG-----------------------------------------------GLIF
NSYMLPPLFLEPGDLR----LLDVDNRVVLPIEAPIRMMITSQDVLHSWAVPTLGLKTDA
IPGRLNQTTFTATRPGVYYGQCSEICGANHSFMPIVLELIPLKIFEMGPVFTL-------
---------------
*
>P1;cox2_ktun
cox2_ktun  229 bases  CF163387 checksum
----------------------------------------MAFWSQWGFQDGASPIMEQL
IFFHDHAMLILIMIISLLSYGAVSLMNN--------SFLS--------------------
------RSTLESQEIEIVWTILPAVVLIFLAFPSLQLLYLLDELE-EPALTIKVVGHQWY
WSYEYSDFL-----------------------------------------------NLEF
DSYMISLEDLEEGDYR----LLEVDHRSVVPMKTKVRVLVTAADVLHSWTVPSLGVKADA
VPGRLNQLSFFANYPGVFYGQCSEICGANHSFMPIVLEVVDSSSFIKWIMFNGEA-----
---------------
*
>P1;cox2_lter
cox2_lter  228 bases  FED6B23E checksum
----------------------------------------MPNWGQVMFQDAASSVMLQL
VSFHDHALLVLTLVLTVVGYALLALMLN--------KQVN--------------------
------RYIMEAQTVETIWTILPALILLVLALPSLRILYITDEVS-QPSITVKTIGHQWY
WSYEYTDFL-----------------------------------------------NVEM
DSYMLPTSDLLPGDYR----LLEVDNRMVVPMQLEIRMLITAADVIHSWTVPALGVKVDA
VPGRLNQIGFTTTQPGVFYGQCSEICGANHSFMPIAVEAINTKSFMSWVSNFKP------
---------------
*
>P1;cox2_marpo
cox2_marpo  251 bases  C54FE1C3 checksum
---------------------MNLIWIFP------IAFCDAAEPWQLGFQDPATPMMQGI
IDLHNDIFFFLIVILIFVLWMLVRALWHFHYK--RNPIPER-------------------
--------IVHGTTIEIIWTIFPSIILMFIAIPSFALLYSMDEVV-DPAITIKAIGHQWY
WTYEYSDYNSS------------------------------------------DEQSLTF
DSYMIPEDDLELGQLR----LLEVDNRVVVPAKTHLRMIITSADVLHSWAVPSLGVKCDA
VPGRLNQTSIFIKREGVYYGQCSELCGTNHGFMPIVVEAVSLDDYVSWVSNKLD------
---------------
*
>P1;cox2_metse
cox2_metse  248 bases  241D5B38 checksum
-----------------------MTNLLNNWLIINQFGYDLPEPWQLGLQDAAHPVMEEI
IFFHDQVMFILIIIITTVLWLIVKALSG--------KAYH--------------------
------RYLVDGTLLEIIWTIVPAIILILIAFPSLKLLYLMDEVM-DPALTIKAIGHQWY
WSYEYSDYQTE---------------------------------------------TLEF
DSYMVPTSELNKGDFR----LLEVDNRLVVPINTHVRVLVTGADVLHSFAVPALAVKMDA
IPGRLNQTGFFIKRPGIFYGQCSEICGANHSFMPIVIEAVSLDKYINWVLSGSDE-----
---------------
*
>P1;cox2_picca
cox2_picca  247 bases  6F318C14 checksum
-----------------------MLLIMNN-----MMNNDVPTPWGVYFQDSATPNHEGI
MELHDNIMFYLVLILCLVSWLLFSMVKD--GS--KNPLPHK-------------------
-------YLVHGQTIEIIWTILPALVLLVMAFPSFMLLYLCDEVI-SPAMTIKAIGTQWY
WKYEYSDFIND------------------------------------------SGETIEF
ESYVIPEDTLEDGQLP----LLDTDTSIVCPVNTHIRFIVSAADVIHDFAVPSLGIKIDA
CPGRLNQVSALIQREGVYYGQCSETCGVAHSAMPIKVEAVSLKEFLTWLNEQ--------
---------------
*
>P1;cox2_podan
cox2_podan  250 bases  E06E0759 checksum
----------------------MFFLINKL-----VMNFDAPSPWGIYFQDSATPQMEGL
NELHDNIMYYLVVILFAVGWILLSIVINYVST--KSPISHK-------------------
-------YLNHGTLIELIWTITPAVILILIAFPSFKLLYLMDEVS-DPSMSVLAEGHQWY
WSYQYPDFLDS------------------------------------------NDQFIEF
DSYIVPESDLDEGGLR----MLEVDNRVVLPELTHVRFIITAGDVIHSFAAPALGIKCDA
YPGRLNQVSVFINREGVFYGQCSEICGILHSSMPIVIESVSLEKFLIWLKEQ--------
---------------
*
>P1;cox2_prowi
cox2_prowi  258 bases  A4C2C0FD checksum
-----------------MKFLLFAYALIPF-----VSFSDAPEAWQIGFQDPATPIMQGL
IDLHHDIQFFLIAVLVFVVWMVSRALYLFHYT--RNPLPEK-------------------
--------IIHGTLIEIVWTITPSLILIFIAVPSFALLYSLDEVV-DPAVTIKAIGHQWY
WSYEYSDYSIA------------------------------------------DDQSIAF
DSYMIPDDDLELGQYR----LLEVDNRVVVPVDTHIRVIITAADVLHSWAIPSLGVKCDA
VPGRLNQIPMFIKREGVFYGQCSELCGTNHAFMPIVVEAVSLENYISWVSNKLEEL----
---------------
*
>P1;cox2_recam
cox2_recam  260 bases  2094EF7B checksum
------------------MFLVALIFIIISYGMVDSLRADYAEKWQLDFQDPATPVMEGI
INLHHDLWFFLILIAVFVLWILLRTLWFFDRS--RGTVPSK-------------------
--------VVHGTVLEIVWTIAPSFILLAIAIPSFALLYSMEEST-DPAITLKAIGHQWY
WSYEYSDYTT-------------------------------------------DSESLAF
DSYMLPESELKEGQLR----LLEVDNRIFLPTHTHLRVLITSSDVLHSWAVPSLGVKVDA
CPGRLNQASIFLKREGIFYGQCSEICGVNHGFMPIVIEAVPLKEYVSWVSSQIQI-----
---------------
*
