>P1;nad3_parde
nad3_parde  121 bases  F26F33AC checksum
------MEYLLQEYLPILVFLGMASALAIVLILAAAVIAVRN--PDPEKVSAYECGFNAF
D-DARMKFDVRFYLVSILFIIFDLEVAFLFPWAVSFASLS-DVAFWGLMVFLAVLTVGFA
YEWKKGALEWA----------------------
*
>P1;nad3_acaca
nad3_acaca  118 bases  250A73C checksum
---------MTLEYIYIFIFFWGAFFISCLLIFLSYFLVYQE--SDIEKNSAYECGFQPF
E-DTRSKFNVRYYLIAILFMIFDLEIMYLFPWSISISTGS-FFGVWAIFLFLIILTVGFI
YEWQKGALEWD----------------------
*
>P1;nad3_allma
nad3_allma  114 bases  34830A20 checksum
--------------MTYLVYIVFTIVLTVGLILVSYLLSQAQ--PDSEKVSAYECGFSPL
G-DARQKFDVSFYLIAILFIIFDLEVVFILPFASVIHNVS-LLGGWITIIFLVILTIGFI
YEFVSGAITDSF---------------------
*
>P1;nad3_apec
nad3_apec  110 bases  EFCC2326 checksum
-----------IFNFLTLFVSILIFLITTLITFAAHFLPSRN-TD-SEKSSPYECGFDPL
N-SARVPFSFRFFLVAILFLLFDLEIALLFPLPFSVFFH--P--IHTP----LILTVGLI
FEWVQGGLDWAE---------------------
*
>P1;nad3_arath
nad3_arath  119 bases  E0030341 checksum
---------MMSEFAPISIYLVISLLVSLILLGVPFPFASNS-STYPEKLSAYECGFDPS
G-DARSRFDIRFYLVSILFLIPDLEVTFFFPWAVPPNKID-LFGFWSMMAFLFILTIGFL
YEWKRGASDRE----------------------
*
>P1;nad3_balca
nad3_balca  116 bases  CC6A916A checksum
-------------MNSFLIYLLIAITLSFILSIVGHRLPTRN-MD-QEKLSPYECGFDPQ
A-SARLPFSLRFFLVAILFLLFDLEIALLLPFPAALSARDPQLSFTLAFLILLILTIGLI
YEWMEGGLEWAE---------------------
*
>P1;nad3_chocr
nad3_chocr  121 bases  CADB912A checksum
------MKLIFTEYSAILIFFAISSLLSSVIFLLSYFLIPQK--PDQEKVSAYECGFNPF
D-DARATFDIRFYLVAILFLIFDLEISFLFPWSLVLGEIS-IIGFWSMIVFLVILTIGFI
YEWYKGALEWE----------------------
*
>P1;nad3_drome
nad3_drome  117 bases  F5A025FA checksum
-------------MFSIIFIALLILLITTIVMFLASILSKKA-LIDREKSSPFECGFDPK
S-SSRLPFSLRFFLITIIFLIFDVEIALILPMIIIMKYSNIMIWTITSIIFILILLIGLY
HEWNQGMLNWSN---------------------
*
>P1;nad3_human
nad3_human  115 bases  EF893350 checksum
-------------MN-FALILMINTLLALLLMIITFWLPQLN-GY-MEKSTPYECGFDPM
S-PARVPFSMKFFLVAITFLLFDLEIALLLPLPWALQTTNLPLMVMSSLLLIIILALSLA
YEWLQKGLDWTE---------------------
*
>P1;nad3_ktun
nad3_ktun  120 bases  3F1E2D81 checksum
-------------MFFVLSLVLFTFLLSLVLLSVSLSLTKKK-MMNREKSSPFECGFDPK
S-SARLPFSMRFFLITVVFLVFDVEIVLLLPYLFSSGWSIDVFSLVGSMMILVILIIGVL
HEWSEGSLEWFSSSN------------------
*
>P1;nad3_lter
nad3_lter  117 bases  343B9B50 checksum
-------------MILTALSSAIALLVPIIILGAAWVLASRS-TEDREKSSPFECGFDPK
S-TARIPFSTRFFLLAIIFIVFDIEIVLLMPLPTILHTSDVFTTVTTSVLFLMILLIGLI
HEWKEGSLDWSS---------------------
*
>P1;nad3_marpo
nad3_marpo  118 bases  3C3D193F checksum
-----------MEFAPIFVYLVISLLLSLILIGVSFLFASSSSLAYPEKLSAYECGFDPF
D-DARSRFDIRFYLVSILFIIFDLEVTFLFPWAVSLNKIG-LFGFWSMMVFLFILTIGFV
YEWKKGALDWE----------------------
*
>P1;nad3_metse
nad3_metse  118 bases  AC9245CE checksum
---------MYTEFYGILVLLIFSVVLSAIISGASYILGDKQ--PDREKVSAYECGFDPF
G-TPGRPFSIRFFLIGILFLIFDLEISFLFPWCVVCNQVF-PFGYWTMIVFLAVLTLGLV
YEWLKGGLEWE----------------------
*
>P1;nad3_picca
nad3_picca  148 bases  B5CC1F48 checksum
MLNYFVYPYGIENDMGMKFYMMLVPMMSMVLMMINYMMTNKS-DNNMNKTGPYECGFDSF
R-QSRTTYSIKFILIAILFLPFDLELTSILPYTLSMYNTN-IYGLFILLYFLLPLIIGFI
IEINTKAIYMTKMFNRNVKSMTSYVKYNNKI--
*
>P1;nad3_podan
nad3_podan  137 bases  AADFEF34 checksum
-------------MSSMTLFILFVSIIALLFLFINLIFAPHN--PYQEKYSIFECGFHSF
LGQNRTQFGVKFFIFALVYLLLDLEILLTFPFAVSEYVNN-IYGLIILLGFITIITIGFV
YELGKSALKIDSRQVITMTRFNYSSTIEYLGKI
*
>P1;nad3_prowi
nad3_prowi  117 bases  9F577378 checksum
----------MYEFLGILIYFFIALALSLLLLGLPFLVSTRK--ADPEKISAYECGFDPF
D-DARGRFDIQFYLVAILFIIFDLEVAFLFPWALTLNKIG-YFGFWSMMLFLFILTVGFI
YEWRKGALDWS----------------------
*
>P1;nad3_recam
nad3_recam  122 bases  34B45160 checksum
-----MNTMILSEYLSVLIFFIFSFGLSCIILGLSYVLATQN--ADTEKLSPYECGFNPF
D-DARGAFDVRFYLVAILFIIFDLEVAFLFPWAVALSDVT-IFGFWTMFIFLLILTVGFI
YEWKKGALDWE----------------------
*
