>P1;nad3_parde

------MEYLLQEYLPILVFLGMASALAIVLILAAAVIAVRN--PDPEKVSAYECGFNAF
D-DARMKFDVRFYLVSILFIIFDLEVAFLFPWAVSFASLS-DVAFWGLMVFLAVLTVGFA
YEWKKGALEWA----------------------*

>P1;nad3_acaca

---------MTLEYIYIFIFFWGAFFISCLLIFLSYFLVYQE--SDIEKNSAYECGFQPF
E-DTRSKFNVRYYLIAILFMIFDLEIMYLFPWSISISTGS-FFGVWAIFLFLIILTVGFI
YEWQKGALEWD----------------------*

>P1;nad3_allma

--------------MTYLVYIVFTIVLTVGLILVSYLLSQAQ--PDSEKVSAYECGFSPL
G-DARQKFDVSFYLIAILFIIFDLEVVFILPFASVIHNVS-LLGGWITIIFLVILTIGFI
YEFVSGAITDSF---------------------*

>P1;nad3_apec

-----------IFNFLTLFVSILIFLITTLITFAAHFLPSRN-TD-SEKSSPYECGFDPL
N-SARVPFSFRFFLVAILFLLFDLEIALLFPLPFSVFFH--P--IHTP----LILTVGLI
FEWVQGGLDWAE---------------------*

>P1;nad3_arath

---------MMSEFAPISIYLVISLLVSLILLGVPFPFASNS-STYPEKLSAYECGFDPS
G-DARSRFDIRFYLVSILFLIPDLEVTFFFPWAVPPNKID-LFGFWSMMAFLFILTIGFL
YEWKRGASDRE----------------------*

>P1;nad3_balca

-------------MNSFLIYLLIAITLSFILSIVGHRLPTRN-MD-QEKLSPYECGFDPQ
A-SARLPFSLRFFLVAILFLLFDLEIALLLPFPAALSARDPQLSFTLAFLILLILTIGLI
YEWMEGGLEWAE---------------------*

>P1;nad3_chocr

------MKLIFTEYSAILIFFAISSLLSSVIFLLSYFLIPQK--PDQEKVSAYECGFNPF
D-DARATFDIRFYLVAILFLIFDLEISFLFPWSLVLGEIS-IIGFWSMIVFLVILTIGFI
YEWYKGALEWE----------------------*

>P1;nad3_drome

-------------MFSIIFIALLILLITTIVMFLASILSKKA-LIDREKSSPFECGFDPK
S-SSRLPFSLRFFLITIIFLIFDVEIALILPMIIIMKYSNIMIWTITSIIFILILLIGLY
HEWNQGMLNWSN---------------------*

>P1;nad3_human

-------------MN-FALILMINTLLALLLMIITFWLPQLN-GY-MEKSTPYECGFDPM
S-PARVPFSMKFFLVAITFLLFDLEIALLLPLPWALQTTNLPLMVMSSLLLIIILALSLA
YEWLQKGLDWTE---------------------*

>P1;nad3_ktun

-------------MFFVLSLVLFTFLLSLVLLSVSLSLTKKK-MMNREKSSPFECGFDPK
S-SARLPFSMRFFLITVVFLVFDVEIVLLLPYLFSSGWSIDVFSLVGSMMILVILIIGVL
HEWSEGSLEWFSSSN------------------*

>P1;nad3_lter

-------------MILTALSSAIALLVPIIILGAAWVLASRS-TEDREKSSPFECGFDPK
S-TARIPFSTRFFLLAIIFIVFDIEIVLLMPLPTILHTSDVFTTVTTSVLFLMILLIGLI
HEWKEGSLDWSS---------------------*

>P1;nad3_marpo

-----------MEFAPIFVYLVISLLLSLILIGVSFLFASSSSLAYPEKLSAYECGFDPF
D-DARSRFDIRFYLVSILFIIFDLEVTFLFPWAVSLNKIG-LFGFWSMMVFLFILTIGFV
YEWKKGALDWE----------------------*

>P1;nad3_metse

---------MYTEFYGILVLLIFSVVLSAIISGASYILGDKQ--PDREKVSAYECGFDPF
G-TPGRPFSIRFFLIGILFLIFDLEISFLFPWCVVCNQVF-PFGYWTMIVFLAVLTLGLV
YEWLKGGLEWE----------------------*

>P1;nad3_picca

MLNYFVYPYGIENDMGMKFYMMLVPMMSMVLMMINYMMTNKS-DNNMNKTGPYECGFDSF
R-QSRTTYSIKFILIAILFLPFDLELTSILPYTLSMYNTN-IYGLFILLYFLLPLIIGFI
IEINTKAIYMTKMFNRNVKSMTSYVKYNNKI--*

>P1;nad3_podan

-------------MSSMTLFILFVSIIALLFLFINLIFAPHN--PYQEKYSIFECGFHSF
LGQNRTQFGVKFFIFALVYLLLDLEILLTFPFAVSEYVNN-IYGLIILLGFITIITIGFV
YELGKSALKIDSRQVITMTRFNYSSTIEYLGKI*

>P1;nad3_prowi

----------MYEFLGILIYFFIALALSLLLLGLPFLVSTRK--ADPEKISAYECGFDPF
D-DARGRFDIQFYLVAILFIIFDLEVAFLFPWALTLNKIG-YFGFWSMMLFLFILTVGFI
YEWRKGALDWS----------------------*

>P1;nad3_recam

-----MNTMILSEYLSVLIFFIFSFGLSCIILGLSYVLATQN--ADTEKLSPYECGFNPF
D-DARGAFDVRFYLVAILFIIFDLEVAFLFPWAVALSDVT-IFGFWTMFIFLLILTVGFI
YEWKKGALDWE----------------------*
